//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionInfo
    {
        public int Id { get; set; }
        public int SalesmanId { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
